### python 복습

### Markdown 수식 작성
    - LaTEX 태그로 작성 가능
$$
    \begin{pmatrix}
    1 & 2 & 3 \\
    4 & 5 & 6 \\
    \end{pmatrix}
    +
    \begin{pmatrix}
    5 & 5 & 5 \\
    5 & 5 & 5 \\
    \end{pmatrix}
$$
$$
    \begin{pmatrix}
    1 & 2 & 3 \\
    4 & 5 & 6 \\
    \end{pmatrix}
    \times
    \begin{pmatrix}
    5 & 5 \\
    5 & 5 \\
    5 & 5 \\
    \end{pmatrix}
$$

### Numpy
    - 데이터를 행렬로 표현 (영상 포함)
    - 선형대수/ 통계 연산 위한 라이브러리
    
    Pandas: 데이터 분석에 가장 많이 활용
    Numpy: 알고리즘 활용에 필수적 패키지 

In [1]:
# 호출
import numpy as np

#### array broadcasting
    - 차원이 다른 연산을 동일한 차원에 자동으로 변형시켜 연산을 가능하게 해주는 것
    - 딥러닝에서 bias(편향) 계산 때 주로 사용

In [2]:
# 초기 가중치 생성
ary = np.array(np.random.randn(10)) # 표준정규분포를 따르는 난수 생성 -> 초기 가중치 생성 때 사용.
ary

array([ 0.32307168,  0.47295344, -0.7088132 , -0.78252726,  0.37949795,
        0.62483666, -0.38728484,  0.08627012, -0.32032156, -0.46011879])

In [3]:
# 편향값 생성
bias = np.random.rand(1)
bias

array([0.26122723])

In [4]:
ary + bias # array broadcasting

array([ 0.58429891,  0.73418067, -0.44758597, -0.52130003,  0.64072518,
        0.88606389, -0.12605761,  0.34749735, -0.05909433, -0.19889156])

### 통계함수
    - max, min, mean, median, var, std

In [6]:
np.max(ary), np.min(ary) # min-max normalization때 사용 -> 데이터 정규화

(0.6248366569177282, -0.7825272576958506)

### Random 모듈
    - seed: 랜덤 모듈의 규칙값, 난수 생성 환경 고정
    - randint: 균등 분포로 정수 생성
    - randn: 정규분포로 난수 생성
    - shuffle: 무작위 섞기
    - choice: 특정확률로 데이터 뽑기

### seed

In [11]:
seed = 603 # 머신러닝, 딥러닝에서 하이퍼파라미터로 사용

np.random.seed(seed)
r1 = np.random.rand(10)

np.random.seed(1)
r2 = np.random.rand(10)

np.random.seed(seed)
r3 = np.random.rand(10)

In [10]:
r1, r2, r3

(array([0.06450168, 0.13338277, 0.10931622, 0.97127506, 0.85101842,
        0.96534748, 0.99727133, 0.93093441, 0.48533923, 0.63427833]),
 array([4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01,
        1.46755891e-01, 9.23385948e-02, 1.86260211e-01, 3.45560727e-01,
        3.96767474e-01, 5.38816734e-01]),
 array([0.06450168, 0.13338277, 0.10931622, 0.97127506, 0.85101842,
        0.96534748, 0.99727133, 0.93093441, 0.48533923, 0.63427833]))

#### 머신러닝 예시
    - scaling 처리 후 return 값으로 ndarray 타입 데이터로 출력

In [15]:
from sklearn.preprocessing import MinMaxScaler # 데이터 정규화 = scaling 처리
import pandas as pd

X = np.random.randint(1, 100, 10).reshape(-1,2) # 5행 2열 데이터 생성
df = pd.DataFrame(X)

In [17]:
scaled_data = MinMaxScaler().fit_transform(df)
scaled_data, type(scaled_data)

(array([[0.07792208, 0.31707317],
        [1.        , 0.34146341],
        [0.88311688, 0.90243902],
        [0.        , 0.        ],
        [0.57142857, 1.        ]]),
 numpy.ndarray)

### 머신러닝 예시
- 초기값을 임의로 생성하여 zero 생성하여 대입할 때 다음과 같은 행렬을 작성하시오.

In [18]:
zero_ary = np.zeros((4,4))
zero_ary

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
rand = np.random.randn(4)
rand

array([-0.66308499, -0.11570255, -0.0769512 ,  1.30625445])

In [27]:
for i in range(4):
    zero_ary[i][i] = rand[i]
zero_ary

array([[-0.66308499,  0.        ,  0.        ,  0.        ],
       [ 0.        , -0.11570255,  0.        ,  0.        ],
       [ 0.        ,  0.        , -0.0769512 ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.30625445]])

In [33]:
import numpy as np

w = np.random.randn(4)
shp = np.zeros((4,4))

# 연결성 생각 (숫자 지정X)
for i in range(shp.shape[0]):
    for j in range(shp.shape[1]):
        if i==j: shp[i][j] = w[i]
shp

array([[ 1.49373501,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.06130062,  0.        ,  0.        ],
       [ 0.        ,  0.        , -2.35909253,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.10284966]])

In [35]:
# 대각 행렬 생성
import numpy as np
diag_matrix = np.diag(np.random.rand(4))
diag_matrix

array([[0.6723856 , 0.        , 0.        , 0.        ],
       [0.        , 0.30898822, 0.        , 0.        ],
       [0.        , 0.        , 0.3045959 , 0.        ],
       [0.        , 0.        , 0.        , 0.01266297]])

### Function
- 반복성 줄이고 함수로 선언한 연산 재사용
- 객체 지향 언어의 큰 장점 

```python 
def 함수명(파라미터):
    return 출력값
```

In [42]:
# 리턴 선언 X 사용 경우 -> 함수가 연산 도구로만 사용될 때
# 전역 변수, 지역 변수
num = 603
print(num)

def today():
    num = 604
    print(num)

today()

print(num)

603
604
603


In [44]:
num = 603
print(num)

def today():
    global num
    
    num = 604
    print(num)

today()
print(num)

603
604
604


#### map 함수와 pandas apply는 유사한 기능.
- 순서가 있는 데이터값에 함수를 모두 적용하여 결과 출력하는 함수

```phthon
map(적용할 함수, 입력할 데이터)
```

In [47]:
num_txt = "1 2 3 4 5 6"
num_int = list(map(int,num_txt.split(" ")))
num_int

[1, 2, 3, 4, 5, 6]

#### lambda 함수
- 간단한 연산을 구현하여 일시적으로 사용하는 함수

```python
lambda 리턴: 연산
```

In [51]:
seq = np.random.randint(1,101,10)
q = list(map(lambda x: x//3, seq))

seq, q

(array([68, 37, 11, 95, 38, 48, 60, 63,  8, 78]),
 [22, 12, 3, 31, 12, 16, 20, 21, 2, 26])